---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter
spec:
  staticConfigs:
    - targets:
        - ricey.internal:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: node-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: smartctl-exporter
spec:
  staticConfigs:
    - targets:
        - ricey.internal:9633
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: smartctl-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: rk1n
spec:
  staticConfigs:
    - targets:
        - rk1n1.internal
        - rk1n2.internal
        - rk1n3.internal
        - rk1n4.internal
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: rk1n
