apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
data:
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:tSe6T7uHJfQ+AALmdyjd1IDfW5fh2LuG76U7dCzfRGGEWqkCUqiEesUAEtY=,iv:EuD6215byIqM7+Rp5kGCzZhx9KE79P5dCg1Jw9DIhZI=,tag:p78hBicuNLYU7YbzxIeJ5Q==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:9204PgAU07BNRXlTCWQCIcLEzI1YwOvef+x4MIK2AeF/n+cBT4pv9hLQubA=,iv:nkks94W1C04LblP9hjnJCIGLa+WKXKt8mxFgEAF0sbQ=,tag:dMr4CcJD41AcQBjj1+zNtA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRlYzckNCdjEvS3FKSDhL
        K0FNY2RKbE41aEswVTFKdHBNVWo4Zjk0U1Q4CjBaRC85c1BzNTlMWjJFSmRTaEVp
        bFErQkUrdXljNzJOcG5ZRUxIVG5uYncKLS0tIFZJMXJ5eXpqeVJLYnozRnh3T0I3
        Sll6US9mL2Ryd3FOYnlQdEEvSjdRTGcK/D057bQdMW/7ATSGBrNrHQY2qV/pN4g3
        dWtXrxdpwTYmhBnOETwgutzWVijV3NSjMU866tF2Ghay5OHDFcEo3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-10T01:23:18Z"
  mac: ENC[AES256_GCM,data:ph89Gc1+fGvAHf4shrRmKyCD0HRr2XLuywF3B8xTRelepP9haL8RSXwqqORpRQ5/ADTMf8ae0bMDknw5RyPGKDXxuCh9hwVGXLf16d1jbHWnHA/Hv17gUfsr3Xm5Q8kQ04SBfVzOcMuuvai7rYoxUC0OlYbXaOhsJXRvU9v1vXM=,iv:VdfYwDS77QsU1r1G5h60OcPAvGqVOkTuqJF5tKvhFqA=,tag:imK+A0UG1aybLKQdLQpS7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
