apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
data:
  ALERTMANAGER_PUSHOVER_TOKEN: YWhycXI4YzkzYWlvM2J5ank2bnJ0dnlnNHFwNGR0Cg==
  PUSHOVER_USER_KEY: dXRqYTNhcXFkZnh6dDN1ODU2d2k0NGQya3IxZ2diCg==
