apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
data:
  username: ENC[AES256_GCM,data:oV+hnEA62Kc=,iv:D+QWnLhjk7DZ53QA1zmrjdU6Qgtl3ojkPk2arjbaAVY=,tag:q+TZ3/JV897H6DE5qvmVaw==,type:str]
  password: ENC[AES256_GCM,data:OIjxzabEu6s32+oOIqcUpjPzjtoVry2k,iv:wW9UCDX5XZxLholxQCXe3FyblHD+O1CdDz8Q1/wQpvg=,tag:7i4DS0dslgd1MOVblXnLHQ==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRE42cE1YWEp0NWxmUlJv
        UWJGaFBTTDJHYVpjY2oraEdxL1hDY014VTEwCnUvSkpiTGpTQS9MQWhDZjJBd0tH
        UWNqamhXWUl5QkduQmpSeWVCYUdseTAKLS0tIGNQNTVBd0xsYm9Nb3E5dGpGakV4
        cWxBRnVCWjkyN3JFMXZqY0pQN0c0ZVkKWej29owbVJZnaIUTaGQIVDm51aD/cHYd
        RdkCnnt5P0OrxErVuxeyGOloRScoX4nv+q+iCf+S+vecccus9coyMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T02:43:11Z"
  mac: ENC[AES256_GCM,data:mIcwnkKvuahcrNpMSOaLegJrmAp7CbrrToLf+VYnEaEaE/nWcgv+sLwNehMlqW7JeLI/UBg5dwhtCDPnyXIOxlshdAhrll6sAVNTgBslVRGllf+FLJdFSYvESqGNBEd0gLwiuLyZcpeFpHwpo2Ey01lvL95vpgJDT9Ap1vJTUME=,iv:cfgBi7SxhQnzS4FMnz0Sf7Jzdpo6d6DSUgAex0WimZ0=,tag:iUGH1omOs8MriM4Gn1r4JQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
