apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:k32CUrIaOsPFgOcotKKd6hZvBepsrpRWct8Qftppea6aLjnbIoE2cA==,iv:9LFgpqy34e0oG/CwId2rduYqEXhlua/wm+5N9xzt7cc=,tag:3UP6cPPZ23irpLeJX/lCbA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTW8zN0NvN2dlZGpiT01T
        NW9UNE9LQ29nNzFzWnZkSzNpZDNmMjA0N0cwCmh2M0VHZCthZEE3ZVMzSUd0SVJL
        dXBNNWVPTHM5czdtbWtVSnJXYk1XUGMKLS0tIGE2WGtEaFlSK2E4MUM0ZG56bFh0
        U3YvSkxYUHI2NUl0MktZMXNJNjRhY2cKxv3IqXT/DkHd8h/CTSJsDPv8W4Sgh2dM
        JZ14clTssUfFunqwj/hGC8VeGK3yJTGvE6RA4/9xSCgZt9UTnszQRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T15:40:19Z"
  mac: ENC[AES256_GCM,data:hrmJFsVqZhJunBW7fbwzHmrPrgNibgUOYpqoNL69wOp5rhdxFooxvIUaVVsF2lqLX1uihP0mUiPWjEP124X5jvjT1hci9ABiD3T91/RKGXD6K/WLvVgcRa2g7p7zk2iMr9HtKOgfWsnDX8uL7R/YZRQ8LNWdDaCAv1iTUfc05aw=,iv:4WJizCpV5SIC0YuOhH6FTA9pnk18i+T2V3+X/CfL+PQ=,tag:ZBwhkfsogCSVspfI6nN9ZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
