apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
data:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:4J8X1m1GbDtEn4+kM/txaQ==,iv:Xik7VfUDHDfitJrSQksFSOck35JANvWWGB9sdBh2FME=,tag:EVffH9eAKKcXvaZ50NYviw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:78fQCuliMeIWCKrcFtM7oXkfWUb4plrE0hDkyIJ6d7EvWSig,iv:pEa70/DGwHuEiPxcypMp/AhDzTXrgVpO7ucqwyJo5E0=,tag:KI58B+GovxzgbaP9VQrZuQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:3alFZIepbwjJlEMdireX4lD5hzYmr5pRsPlZ5uJIh7Om3+r6,iv:k9F6wRw7yP5WSBWgi78FmCPvapciJ9OW0TtP6a+fPBg=,tag:TXmuB9S1VfjtQ0lNciGYag==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc1dZNzZoQ0tLSEtLU0xk
        SmNDbXNrbnY5eFlyMm9vUldFbC9kL2VBV0dRCjNEQjFxV0dPQU5QYTFsSHBrQ1Zj
        MnB1WEpHbHpzRlRONWk2ZmY1VkFtVmcKLS0tIFRvcWhoNW5PSnl0MUlEeVRLcTdJ
        ZlRyZ2labTBGSUpaOFRqSklBTndva0UK9gXdk40Bo9l6j3CTM/BKrHgM/zptfSCD
        kYonLscfShlassPWdQ8FWQYpV/l9Xt0h0E14KWQva2cWIFDacghTcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T17:57:30Z"
  mac: ENC[AES256_GCM,data:vm14z7oo7YRDF/hhYysleNDlpwXyL8R1r0+GxCtCAwza1UenUPrAatKG6LnV03APWJnTNu0QtTaKaWd2mXZnUDzfi3BPtiQD3kAy9T7qhSHuWgxwlDllfcWlV8s0RS3UcHFFHh2Yxlp9+Ji5DbfctRMQIEl9DFiefnZUE0H8jhM=,iv:LwNiwD5J7Up9Q8IVZyubcNzxocMgoR7bn2nexrYQoHc=,tag:a+qljt4LewzKZvW3x25M/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
