apiVersion: v1
kind: Secret
metadata:
  name: github-status-token-secret
data:
  token: ENC[AES256_GCM,data:Wn3I8aJvxemuzrKLH+iSLzrKa5Ax4mQm4xn967rbrRzCxKh7dVmxog==,iv:DKLaVbbQsux494BBTWgKRSYSgGuQ0Xo5LNXXpMadGe4=,tag:HPGghshGgVqlRThtemuCaQ==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRFM4WkRkRGdkTVRENnk0
        bE9Lb2dQdWdyRXBwZVBlRk9xNHB0YTBIdjBBCjVMem13UWdLWTYva25pZlhmKzV5
        cTV0cEhTbjluUVhaaTJIS0c1ZVJEUHcKLS0tIGpXL00rOE5xOHpjWG1hZDNOSDc4
        cFdnK1RLbkQ0dEFjV0ttM3FoZ1dXOVkKa3yen9H2wpqDpekf9AIMbFBSCb9dOqrH
        yH1+Q9JRmhPCB/FSNas0C0kAsEGD8VtOZAYTDNUa+ocKsn3rNmK0gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T17:49:56Z"
  mac: ENC[AES256_GCM,data:4IjRCgx3cmpoTeMZGmZ7wt0UQ4NUYw69SAj6ZsUx0jq5qid6AHytHVRVToYPEDQIV6/9ILSDBH9shbB2E0zrDzg15usMxQMbMfL8Vr7hyTRuTwNwhVMn5vGWOKXu7wh5NmXBIMQ2reMbSEob4a4weIBM938YkVWzHDPdYtgMONk=,iv:P7TPFyb0V6a8cO+zPJ9zjkJaEWrZR65waZDSQ3ftYyk=,tag:9phipHdEc9ZyuJll2L+xmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
