apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qLgUVPYyO8c=,iv:Ls8LrlL8kTgqASdsvN4C2PabmUtx65YM8XYz18udW4A=,tag:l5C5/oP9r7hOIgFFqXV/rQ==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ1dxNDk3b0F0eXd1UFVE
        cGs0SnZ5RFNWc1VQdEZuNUVGQWVDVWM2WXc4CmQ4K0VOSVRRWWVIRjZGMUR2UEtv
        U2Q1bEpaa1NvZjdTZVFxSjhXdUpuTDQKLS0tIFNHTVlHazhwai83L2ZzeUNFTWk5
        Q1UxQXRKQXBaV0tTalVXQll2QTB1Y2MKLhnEtRRilxbnfer9PtEEeVsISj4sAqHK
        FvCeptC0s8y943cHcma9fBu1Q7MsxS5znwOlJfKH3xBaY2nkAiQqkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T15:40:19Z"
  mac: ENC[AES256_GCM,data:QZqzG3r9K5ysxxEwgaEB1npI2y8H/dskymD230PbcSuLwRIhI7FPjHI8+cfUCXuqRcs/APCgnmpSoFi+ZdPLFNdZikRdiz+TKd7zsX2Owkbves3GcVE3d+UXXirHjwwp75eDVScCYZgLa3JeCs8PDMxTQzZo4wxYQe9ne89QQk4=,iv:tyC/X6Dp175HgCUyVc4FXsmpacOOVkMWG3xjlGnPVko=,tag:lt74fjwttdmVu0uVIU8ZjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
