apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
data:
  email: ENC[AES256_GCM,data:+k7qC0bMu6HKcRjQgYFgla5Av/U=,iv:XmXZI9tI1qumRF8LuU4ftMpBIMeotpQMl2NR0ViH29A=,tag:ACmBtl1IK6mkYBzg7I2Xuw==,type:str]
  password: ENC[AES256_GCM,data:l+1bzpf0tVR1cygITQorgfETnUNlcSC5qyxurZ1lNj03NV+8,iv:YATHbk/EsRnIVUCS+b/5lMZRRApjlnm+yZvDtdgLwK4=,tag:ZyuWQLyRbjNoyoZ/5Cyrig==,type:str]
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:t69VOjctjpfXhl6HffLWr8sddMk=,iv:AveYmvk8NRIiuMmeJVRP7tmSJzBW2nOVq6C1X1JaQ8o=,tag:P9357pc92nkmsNBJgKPwsQ==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:65wNpDhkV1CAfVFmvze26RuOVr+miWjb42XuvulmDETJBjnE,iv:o0yXHMD/qYZP772CWUgyxkLU3VoM2QflRHNuLnr7mBE=,tag:+y1+TFpZMXUh9unaBVQpOA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWTNRR1B6U1FtaVlHd0Fq
        YnZEMVNpZnM0TjJFUXdDRkpmY1QrU3Z6ZVhBClhjVW9PeVI2UmNEVnBTMk1TQXh5
        NytveFliakpkN2lSVDJQaHZLTk8zNFEKLS0tIHFmTFBoakNRdXVid01xaXJxbFRM
        eWJPQjgzTnZKd1RUYndNU2pmTlZ6T0kKTUIMemg0NrW22qjB+CvPARjYrHbjNLS8
        VoSp5kjp3w/2Z5w6POBdT0KMaUqPaSlYT7YiJPAemouIyaXMATskEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T04:39:13Z"
  mac: ENC[AES256_GCM,data:Aix4OR0+ilsiUGu7HfZECrfaar5oNxcv51Wk/JImuepEqkjvm9ILn9Io7KhnA7TgPn2MECMD7zrdPT54VxznOkT4yyAfrtoDol0pikQ1R69yJmQ/KF74tuIJBKJliIQIbMMnh25vNO093w33RlA5UfNU1cy9YuTIyTE9c57nxow=,iv:B6KC2Fapyi/RP99Lh2Bb9NatwymeSQdiVqX3tBDeyk4=,tag:Yl6XSy3NNTNr1EXmXRPTZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
