apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:AanGXpVnRnbVXJBFmyTxUmcjoCKlSRbW7J0rvzJI4Xo=,iv:OtPdgWBmMj6qiz7xm1dlAFVaJdarHCnUcjvxo6eHVuI=,tag:4XX04prDLYw8X2XZJmlDJA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT3VxRHV6MFd1c1h3cUNu
        bmZnRWV5MTNqUHl5empVMTJ0T3JmbkxvR1NNCllJL3FKWC9pcjdpYmhFTERSS2My
        cERKSzJ1QjJWL3hFTTgvWlVGUU85aWcKLS0tIFV6Z0JLL3dvL1lHQUljQ2QrRlJ2
        dVNqZ0RmOU9HMHEzaHZrZ3JkTW9hOTQKS321IiFjKCSkh8oqlEkcwEMZ7Vlg2Wqe
        AMHOkMd/byIOLdDOhhRlUuF/JiDJpY2tft0k1p2yVFaXdas7T4a3Ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T15:40:19Z"
  mac: ENC[AES256_GCM,data:PB5OTIaOZyOKlcVY7eDpQ7JYoxeQOrTAx1MV69YPyZ8v28OkqWHUDWGfxsrB+6jf/ngf/sf37e1m/xC88GflqqrDdolccPHq4W+RMTJ+PfxQlDK0daRr1ApdHIgRlWsXPoHXmYYiBTU7wli9EYDwuTcqYpB0/xm8gybs0+nybBQ=,iv:twD0jIjm0L1OER0I0gfgfY8IOVq/ry9/1bA+GfEheJk=,tag:CHcSOBxA1iF6qLwi9vdcAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
