apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
data:
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:K5ueJi21daA=,iv:mNJOYiYTkz7UvLwmRZJxV+g5oJFNi01rK8c/uT9fMyY=,tag:pFKU3UavzcIhbWr/eO5jkA==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:GL6HEyQ52wozj8ZWFR0CrUMQxZEbqPKsifoM4FNeChDlK74k,iv:/DTBYZfPGVKO2XQca2p8Qy++BV/wGyZQExQqE8kPyH4=,tag:iIwvqRg8BBVOEuQ6V0VgoQ==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV1pFZmpTSUo2QlYvbDl0
        eEF6VFdBSFVnRkVJYzl6NWE2T2ZtVG1vcERBClJrcmRXTEE0OURpOFFUVEZ0cm5Q
        cVNIN0ZCbFV3ODBnL05ka3R0UHl3UjQKLS0tIGp3NnlRUkVlWGQ3VXUzeTVKSEJJ
        bWlUcCtSRjBVMEEyQnRKVlNnMFgzdXMKqqDK1rzXgoOrFZc0kutUOicuQRlJYqxj
        cp9nTu/dcgl3jLX7PQJejYm+XVyKktxzPn2Vtcjt/Mr5FW5HPA57Vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:58:11Z"
  mac: ENC[AES256_GCM,data:sOVr9HB66Pdq+ZXsGpPenugjZ26zocHUEZ01uv/9thpn7TBqX8B1Y5DMy5D2RKW7Dnzp3/cc6elvbRDylnG1kvbvuPHbHT8Bq//QFlfggH86y2NxDj6fI9U79+j8M7r0G+do8U1iO+VbeTKjeppFQgUleOlfa0F5OGY0M7HOEU8=,iv:qRhSay/sNCEYUiVTcn/Ns1t70Y8YyaGZ4TKEEAHFHlo=,tag:w5Dv4WztzbnpocspwDJRhw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
