apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1TtLrRfULh1zeVH2VlI2QjkSlsGnaDwJCtNrTPRiH1BPaLg8HmecB0gYNP65q9DjA6rS/p8VOXVI4WUfAYMznrDCRcOh8zO3GD6OyrpyO4q9zDzPZhc9VOjyKmk4pfTcRBm3PDtGuJQYo3q4MN5jdXUzm01smUfkj5LE+nGI6PjSDXmAyEKk7qLfO8cYx6g2aekdHeQfcMr7Hk7ndPgMKTUwhxhluNf1c0Gfktk+U1FnXi7r,iv:AqD8SSq1gvAziKCZE5TjukiSu+JCUK7XQQVLiSxHQk4=,tag:s9ZODS8Z3vTd9Ar42GXW0Q==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYUlucWNMeHRYQ1htZjli
        Y3VZUU1GdVUvN2tqQmwxa0J6TmZtQ0dHaTFrClkza1lVTjlyeFk5SmVnV0dHNjZD
        VHUxZ3NjMWFHb29EM3NZVnl3c3oyaWcKLS0tIHEvMWo4bXg0NkF0UWptUmZUaUtm
        M3V5cm5YWVlaTHdRSnJRNU9LUGNZRHMKN19tUoYkH0ezEkR6UbcWAwYwnTApdbJo
        jnfxGN/Jfzm7nLFFh6BTH5Pr+Q+0ivnt7o9ZssAgglyBvb0jtRujzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T15:40:19Z"
  mac: ENC[AES256_GCM,data:zIA4Bq5XgKVyJcLPF7tP9int6sNxiJYC8gLMUwMrxgN7ujMl18H23hFmKV1YV16nR6KnnKyAFmAxTDB5rV7LgLdxui2ZFV9nCeMKGoVwf+GfB6D+i3c28q0LM5aA9eY+VdG8OlHyiaFEOr10SWdF4i8dSari8pNzUuvBitnTBnM=,iv:wJhTNUnVdeNTvlkySChgSq+LbRxr8dVRvXz6jp6RPTA=,tag:h3o2QmdWc4q3lqb+TZtd/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
