apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
data:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:MlOCuWwD81gOMnBnKLxUBSOlnbrweVVRY68MO4dUDAk+9X2vxSO4uXlharE=,iv:E65R/oBscwNXCjVNToPl+7AV7YBe2WiRKJi9yV445SM=,tag:AEcpt3HjRLRtIn7lgbAjAw==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:EK4f2Cw8VVIAQtG6hFC3atN+8iVeHJKCVwJ3ZJWGTdvkCrjjAjEwwgjOQNk=,iv:AtAl0trmwupsPpOuFqpad8qhyOHHyOg+vwHdJO+Om1c=,tag:PZO5rtyRnFLBIDOy44vGcg==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza3kvdzI5QzZuSXhLSWVv
        RmgyKzBIOU50bHpURVI3S1U0NEZzZ2tBbVNNCkp6RGVoMXpjbVZIUFc1RDVUZ0VU
        Tm5HTERKa2trNzlpeTB1eXkrKzRPS2cKLS0tIHpQelNnR1hFWHVNZStKZHl2UE8v
        ZksvMmtIOEJYb3cyOE0zQnlvN0IzN0kKnjpzIfHU0qTFla+qZtPAhUAWQ4UslqCn
        kdgk12qPTiCh9940v/gsNPHnSmMwQqJvgazEK6YtQPUjwPPslletnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-10T02:14:27Z"
  mac: ENC[AES256_GCM,data:ogSMGKNPkb/76y2MQRS9pjWvAQ6IM2dqGI9O9Brbb9BM7Ea221Fjs//tXAdrpRmhitbqpzEnqpvSrHAtFrg8IXBLtJhOSz/h3/zQ5ryt5Q0BBHEsNsuju1C76yLTFgemTlRacVsqHy9Tv7+wTgdhdu+4XMYtwUne5GqapN8JvR4=,iv:ZBUELkqTma/tclfqnxfDNMq0vA9Rl3Az3nqFl9TYY68=,tag:Vx4R+U/ZC8kwJxU7ud6Aww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
