apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
data:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:6+D9T9cwWsrDHj0BEnRf/nTiDZHrM+sdptaUvmExkIwzf01h,iv:XJ25v1pTIvkqYdyICSby6Lzl9H3aooaIWTWDyBRwf6Y=,tag:voNeqchIhe6o6rthVGCwDQ==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSnV3blRhd0ZsdGxZSE5o
        eElGLzltMmpqNE1Jbno5VlVMcUNzSmRvOFFVCk1DV3g4RFZHY0QwWVZlUkNtaVVl
        MGl2bjRaMDQ4YlJuQ3ZSVlQxcFhLNncKLS0tIE44Zm9TZ1JwTGN6OGhZMGxSMlVr
        MThPNmY2MTRFNmhGSlVTU1hMOFlDbEEKe/junpiPWI1Af6NFrJY7AW+nQvIOPGSr
        xSWYttq3j/tY/nYVyXAtcXgNIZpOfHU/ODliYBv2KriFJOVumYrnuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T18:27:11Z"
  mac: ENC[AES256_GCM,data:B3INd2xN4iKdhRE36WyBuVkg/7aH902QmUjTwSsRm4X7X12TsAHLy/8nswehAUhj1s+1gCqPdgTdLrGTgNt/aQG4Pk7jovm9HohlUij5C2PbQ65NDYEhjAHGzLeMheHxH91a/s9gc4itTN1ATzRu0BRJflzd+meK/arrpI388Kw=,iv:vREVnxBpbgApUfVgpr+k40iXhD/7q6BqUvBcyU1/k5M=,tag:P1FkFaa89QDZHaH2ydgYpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
