apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
data:
  password: ENC[AES256_GCM,data:pGyM8kN7W5CJK0BU+dK+WDu9vLZFn2l+FX2WdBRCOH4nBTKx,iv:CN95m/dMw5YzMkSdoo91JbGt+KVFSIXjv/EJ+FjER6o=,tag:r5dv7PXUo4drU5Yyw69qGQ==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRXJjcmdwSjJYUWQ2eHov
        a1BJakxZL0p6eFhHVEEzdlloNm4xb2JHVFFZCjFKTTdnUFJoQTI3aDd1VmRURDNB
        VTF6UUNKUFlnNzBKeERBb2pZRFZ1Q0EKLS0tIEVob1JpNnpYZk45a3lkdXJFaXJS
        akpoSmZDTm9FdzdBU2Q3VXI4czcxU1UKiBOgET13P5q02aFF8nbKLmXbBnTwetXw
        Y8Hg8dZw2EmDKinUkJBDjrEUm+BjbMMZBjfvjOoJEu9v+/LvVL19pA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T16:39:09Z"
  mac: ENC[AES256_GCM,data:9sAdpoaBmF6mwAX5MnqTZU5vBIHsbmrHiFFTlcP63mlnB8xCsHBxGzAagItsEwT1sJVD/S905Oq7MqqrxxS/oosYcEOqCVYqKbFSy8rXnOv22Aa6KdJkqpQnavNZcfoH43HtFPXadTdh1VMqENy+B4zWeXvbFyQwZ8Or5Pip7co=,iv:x7ybF8UNWx0II4j+IqqmaCrHcxC8GuRDIthfEpWc7/U=,tag:XuWwVJ1bw2YqHuntPWY5Fw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
