apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  K8S_API_HOSTNAME: ENC[AES256_GCM,data:N9b6oDmrGNyxL/GidcRYjg==,iv:fP+iLajwo0XO2mwxPOVlE0rUz0Uz8cpCbfUQSSPsPxo=,tag:UOlpnkxWU/zMwvDG9q+orw==,type:str]
  K8S_DNS_HOSTNAME: ENC[AES256_GCM,data:oN1PJG2ZupkGl1WCFPrFKQM/SOE=,iv:RLcKbMGtOdpO7WQvbTW+GejjRufEuzYhp0JI4wz87e4=,tag:XlCR52gyf5I0LyAxoTccTA==,type:str]
  K8S_GW_HOSTNAME: ENC[AES256_GCM,data:g+Uk/XM67+XWIQsPvY2uv8p+oA==,iv:4Y9vCuL94SOZ90NRDx9txpJYYx+M3eKWQJBTscYFRpo=,tag:3jxb4f3TfyMGsiLVfONZug==,type:str]
  LATITUDE: ENC[AES256_GCM,data:UQGUX2eY+NaA0A==,iv:2gYnOJ9kETn7pgK8FwP8QceYkM6e+UoCdEjZBDldUM0=,tag:s84LDZNsPfyVOok926VTPw==,type:str]
  LONGITUDE: ENC[AES256_GCM,data:dr2SGuaAN1cica4=,iv:0/M4lcYNQAsobwSiZ1OkUOUdenbk01sI/BfEPltMmhU=,tag:MMNdQ1iJ0bCt4NMHmEwdUA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:bHIdJBK9fYY=,iv:x0ab7vGyqqnQdVMzoOFlThvtz80irOKkXP7IY3mPlBc=,tag:aXzGYqa7xh83ZQEwFli61A==,type:str]
  SECRET_IPV4_BLOCK: ENC[AES256_GCM,data:SkbNe5CXPhHigYl7DqKn,iv:mYPRkPjSfeq4xEdU3mhdqtqJi7TMlE0RspDcnkpIyY0=,tag:TglIEFOkvp+FJ1xYbbJR1A==,type:str]
  SECRET_IPV6_BLOCK: ENC[AES256_GCM,data:pkCZXbDSkd03KS8414mstidbCnLKoMYmwA==,iv:b9OUII3UHx8lWgqfdw+F6QXiisywfJ0X6RczZOp5/lU=,tag:ILcvFOtd8/ZINB8iB3YJrw==,type:str]
  SECRET_NFS_SERVER: ENC[AES256_GCM,data:2ft3KjwyoYcxe8Cu9bk=,iv:S+L6tlT3YdSFHlxWHKOetQASdCl2slF2uU+0YUvfgbo=,tag:n8DDfA39NUQcG6GftU9htw==,type:str]
  TZ: ENC[AES256_GCM,data:jq6G5v4kCDyiE2CWLo9GiA==,iv:coVW3gu0sMD8I7U+E3CEYYJAeymgy9dLlMub1lF22QA=,tag:V0La/z9KRNT78pb7kqpM6w==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQk5YT1dYQXZ3U09lVjZ5
        ekF0OTR0OVdpV0ZDVG43Vkt5dEtHbmI5ZVJBCitrWUk5WmlOTnVZbC9NSUFNMTRU
        bDYyWjl3b0lDdDZOWVFlRWwzZFZVcFkKLS0tIHFrSExyNVVHUWRtNFRvSFh1a2hp
        SFJiNUhKR3lLMHVNWEd4SFpRV3RZcVEKQM4siCCARe6TTtEnQ4IrVt7Mqp9ST1jC
        NQMAozdODtAXI+fq+Q84QsQ88mrq0IlfkZp8LFaBabSslgWxYuzRPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T01:09:30Z"
  mac: ENC[AES256_GCM,data:Go7PM8LJ9Fd42cHCqk8loLzfdUVuKtRG6ra7alLgfoKgyuwuqDoT9arjkTxLNNn19Ed1yhasVRqWd7fM7DPTiu6E3Ygh7vKKYr2A9mPkaubcGVKsFGqA24R9+g7DPzA1FTcNre5hFbPMDtDfURvBD3WstgYqkhyKFfSk1FxK7rE=,iv:Kd+TsjHZ/EJf20wj3qSGRXxlpf6Rv+JS1XTJF952KpI=,tag:NUT9M0nF1x2O55Ie0X5GvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
