apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  K8S_API_HOSTNAME: ENC[AES256_GCM,data:4Yng8D47xgyfAN/NVc/wjA==,iv:wwMFYBdhpI/2Gj/KvVfYFsUaagRqHy1ugCZNu5bGrvQ=,tag:RkoKbVXqPOIAyqkbkD9VQQ==,type:str]
  K8S_DNS_HOSTNAME: ENC[AES256_GCM,data:0T7rt813CreN6l0evOj+8zoeHDA=,iv:Zt2UUhz6f0gaRmaePgg2+5mwq+Mx6wvTq8OlN/MG6eU=,tag:bzjD24G1KJf9+ELXnJdufw==,type:str]
  K8S_GW_HOSTNAME: ENC[AES256_GCM,data:DGVLJxzzimQvz3gWpdQOsVZb7A==,iv:PpRacSA/C1Rifx5zaszQ3yqPsjp8mJRQPks9Enkq3vs=,tag:c2tA+QUxA6b1J7dkauePtQ==,type:str]
  LATITUDE: ENC[AES256_GCM,data:b2eoXDJ2CGCPQQ==,iv:+WRzQgOgKch33YrBbhBo6Ek8xi3ImNkxUe4QnQP806A=,tag:UuHb9Uc8GB4qwsPfgnI6Hg==,type:float]
  LONGITUDE: ENC[AES256_GCM,data:tsyr7n6K/oFkFQU=,iv:802+f249OQ/UlrhDwvhf+rt5X+3l0wFLMTrBdbvVh6I=,tag:MbUBvt1gUACQwrTPnuMSSg==,type:float]
  SECRET_DOMAIN: ENC[AES256_GCM,data:uJJcv9Lyfss=,iv:Rr9m5ArjIZmg+P26s1sfB2BrPMI8EtcLoejrKqPOixw=,tag:c3hssjU5tXNswyAcDLgNTg==,type:str]
  SECRET_IPV4_BLOCK: ENC[AES256_GCM,data:lWhgQSz0IAaIvmyecih+,iv:EIfTD7GHhzzUA9QjeXiZzWWANZuIb7uWe5q7dNGPyA0=,tag:93I7jkbwa/LyIGkyd4rKRw==,type:str]
  SECRET_IPV6_BLOCK: ENC[AES256_GCM,data:jOfnZ9ApCvx//47w7aK29HzItAuCpgP3BA==,iv:SaR9DupodooZuluPtAt8RWX3pr7957vThr/xPPuHMo4=,tag:qT6HEd6QqhZPczp7siLYBg==,type:str]
  SECRET_NFS_SERVER: ENC[AES256_GCM,data:ZLiwvvYTc6tvBOQmcQE=,iv:aO9mtt2cTJULTwbbwePt7RD+TkiZs/Jin2c+LF2F3xs=,tag:hVTypCx9iEo8+5tysxozrw==,type:str]
  TZ: ENC[AES256_GCM,data:HBRU0bM+SHqmplQlsJ+aSw==,iv:amoEt6zkiILPFDjYKSz9IPAs5rWHJMqXmb6MBjUroDI=,tag:iQj2xC3qtOlNUrBQ8I6jQQ==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dTJUZ29YNVJqTE9Id0lZ
        elI3MW9QV0FCc093eXlaaU9zMnV4L05iaTFZCk4xNE81VTZZVmkxQjFPQWxTcDNS
        QUxOTThLbE1UY05hTE1LV2JBYlcyL2MKLS0tIDhoQnpjc3UrSVB6Z29IZldyN05l
        ZTl4emUvdmUybURDZC9zUDJJaFZ6OVkKJtzu+YC4cHL16sQO6+s7qA2ilyOtmZeI
        uMT3ke+wiEMpjrh0pwqGhy/JmGUipZCfsF0KD1mfl4yhsu0zVMMxng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T00:52:52Z"
  mac: ENC[AES256_GCM,data:xUtlnqeFM/9rIxnNQw0FKSMNTD6hUPBLDf98+03GyKn7YD+AYwVPZVUPe7I1CNytFti9poLzK3CLZkezKEaRFdXe5ZGa3CqTHChs50LfepAYNgtEHbOfl1jlcfP46y0IH0HdZ5u9gsGfikm3qeJ8G/sfhfuudXkssdLYLkB/dME=,iv:FG2nhw8HJwph7flwncsYhcUbD8ewJeQozYY8klC4x6w=,tag:Zc2hOlTuzSyui9oTWyWXhw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
