apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
data:
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:w7q+X3EjxJ/7OZKpOMpOS1IlMz+XhZdFlKTDzEmNnac=,iv:roEmGlMyLecz7GG+xYI00Mjk2clZjTNvabW84Aph+Ts=,tag:M77mIloYceDocWM4TjqIiA==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:SFDqTDL/pLRBbcA4MppXqGpDUSqxaqiuOVsfAAN1hWHi+0G+,iv:SjXao9ATEALrOR5A5QA9L1FAoJt8jjIwou9RUniKJBk=,tag:a/IdMDMl+Mk5DdkWNTG6rw==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:3rvl5TWag8MEZZbCTifdvTCTXIlGLtjct1CIp2aHtt89Z2rdp8f1xHVimhaLehTu,iv:qlk0kFmQye0KgMmdHcXMuWr7A5mPV4Yq6p90sZpxTRs=,tag:qwvVD4SQQb4nm25MRYyVyg==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:tEWb58V3kDlJjeqxKNiaocXUxqw=,iv:Zvqx2Mqb9phHsmKCEv/Unt4W8VgkMb2PE2KvynrZRe4=,tag:zPsPjycKRZIgO4QoG6z6/g==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:wegZqMM5GO6PXTsuze8ob4MFwLPntwVEtZ9//TIwzgg=,iv:/1ymA1dxnHQwSrGgAhjIqZmg8xn6IFqaRL47RfQxuvo=,tag:/+30d+19i8z5VEkvHcfYqw==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:jSqC+qq3x/bq/Dkie7ajKGzXWsI3xIyuDfRapG8mVa4FYCllN1hOtnI6kYrGs6IZ7a4lTd9Xfzq26WwxmjBgUsKAtNTUjQR2391BE/I1YvRRx6oN66P5zWXv5NkcYpg+12stThJQjT5+6vqrvO6Xd3oIKkuav1q6,iv:Dg5RMEN+MNY+UUSXcnAE4yarOTa2VuS5zCm42tDjqGc=,tag:7gVphZnlSIB7EC93Ad3zZw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jqplGDbztwc=,iv:J1/H7vqn1lftbLaXzYBnyt5EStA3Wl31R0UeRKSnBko=,tag:96ChRDal0EPWKoiFV7HZDA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/M1m2TjpEKBuKT0K7VHFyFTaaFVmjXjAUJB/YqYnfPBOioVVO+ELrjfctCUqe4GWEHBgFNXMHX0=,iv:tRj2lSHEkaZCP+AOjCMxpD+1I+oiUvTwrsjv+xm96Gk=,tag:Yq5CmMZDmdBMxuTHM8dYdg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:ulhZJoO598Q=,iv:DSKEKydioXk20fzwzUe3qGDy3/Lu9HrUfWkO1gr3Bmg=,tag:M/IQg375tSPhs83ZUgTaug==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ig29ITvH/DRQOklvU7tg/JfySx6b8XM2sAhnz+7tzLvY6sQ1,iv:kYMdKmWWLI9+aGliUpBNUYxO3fLgZ/N1ZO+EgD/qAU0=,tag:FNk6US1Yx9y16hYtyAHKug==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pW4fDfX8cchiTaSSq7U02dBnY2T3kClHPD0aeBGgeN3oElsA,iv:xrQOUYeOcoq8rZ/HZXh4DqqGeYHtWzU6aSzYOfV9eGs=,tag:bNpK9khkShPPukhR6HRrWg==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUWpRcUdnWjdsS0tBdTR6
        UEZFZUdpcm9nektORDcwdktRS0xIZTN5SDBNCmNpMTRYSGNvcWpOSTgyMDZITWM5
        SzBDN3B4amhFWVhXaUNtK0laNk5xSDAKLS0tIHRCNlhyWDB0ZzEwSU13RnhoNjJw
        Z0x5a09IanFUMHNweVpSODJPQWpxTzgKnA5nIjtrcOHDmUSwddPNfcJOu3PhE8VR
        OylRaJXXjQg0y+Rj21KBXDdMQx0zRnsNLzzlck1ij7tDFaHVXgROaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T06:29:31Z"
  mac: ENC[AES256_GCM,data:LHi1GOIN1uaGKDk1bNVWdI5epguVezi452LUWvysf3+2xvA3Lb6IFiNq8Ed1ObS6/gqrO4wyjFcl5WSPw6xxokrlN2WtKcNn7fZsajkk95eUUcResdbo1mksk+TAgb8KiyaV1j6uk8ReA+aQ5gd3XV5bT1tlOMiMi95ZmcX06cw=,iv:3bVOcSKN73L1EpEAyr4vXFJbkZ/sBv9j/xpxzkykIaA=,tag:sDOEB4qwghgQB9xIwVVu3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
