apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
data:
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:X870pUg6YvIUQiTd8m1R/YY9zl8=,iv:TgUriSIsX4fstSqY8fkSCuFsKnnQgGzq4ojc/BV+eAc=,tag:gY7E2sy60GFpUpM3DWwUCg==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:Ag18EHiQNTZRUxy86swCy6/x7eSLZzWp,iv:xJ5AL9N2GbAt6mUgBeVfHXh1L6n7WgMpBCwXaa80gXA=,tag:EeAczMnsD5E62RtpyAmhPw==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:PB7ZJfqL1ngquE0hU3AuTNAeDsVqMLloX4qMZeFOmUaL,iv:BGHLobB4jY5XFbMi+ytXfV6sPIzNDG4dLcfDiUtFvBE=,tag:FPsFEP/DNosbLdaatCfU+A==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:6pBpe7uSPaeCWYDEtD4=,iv:/CYleWOrUsYTXrhJ7gPPiYHMhQQCdyz9x0ljvr7AoDg=,tag:mw/m5XzJqpXNwF+B1hPEHA==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:xDtM5hsdL7CgL7ZGGrxIMN41LT0=,iv:7sm6z1fqUTFKWymQRObC8Mblo/bYy++5yEP3PHNb4yE=,tag:I0h4dHKmtx7I2tOZYVUOKw==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:g5czJCGfgB9OFPTW7vSGBAoluXyW8XjsYs3ABoELe/qgnxrJACP6X9XSroTN1pxTmFqGL2pBYl2P7+TY91LKBnZjC+4xlrGIJrOlDe2wDp9J7aaAusAe,iv:0NoYQ7G7ArC0KkwdXR5YSxmFt6UwE+lqL4TYvsRlko8=,tag:1tzl0nkwd38wOT6q8F7r8A==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:92d7JSY=,iv:SBA5LRF8ts7AO+MsilDmnd99BJMhFoDkT9QCQQGvNKo=,tag:FzPWbgYpxr1deinmi8mNEQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:6XTc5gBX1ei6JNgb5f1Bsu0vBq9NbWOW0mhLXgUxhjY32ULAwFYF,iv:Xf0ElEaYz/UmKn5Xr/+xOh2EmMmreqg62Gdp8E67pNY=,tag:orRhw4zAt/sIv0KrTQlZ5A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:QuUn5ew=,iv:6X37CSm3cn+nFWpUUOV/KT+7v1KB6v29wV75MSN7CFg=,tag:E7DufpK0UBNkC4eVPh3FMQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:EjTZi6VtDq+0qsC8Vc/HZgbW+vg7SRIC,iv:D37SK70DdaGkuPYymng6XzKSD13af71RgojOtPdNdvs=,tag:MDImOKZ3xwe8m90HSnbuBA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:FzJj4w4Wzu6/mA4mvR5lPXDSnjp3pgac,iv:G+3gHmUkdyg0Gpf9ugHHVW2fXMPPCNpfFKCG5sUqqG0=,tag:j/dUqU2ToKD0F1eNxxUQIA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eGRtQVpqcXRWRFJpVC90
        d0xzOEZKYkNlQjdONCtRZEpWekw2ZWY4alNzCnh3SElIckRveTVxL3hVaXByd3Yv
        U0ltSktzQVRpNmZ3bzJENk5nckRKd0EKLS0tIHdDYW1QYm9JVXdvb2dpaGx2dHli
        SVNINnlEemM3MmVaT2NLVjV5UzA3S3MKEgkvbENJPY200IdVklmm+l9kqwIAtCLD
        ichWto4JoUxZ4m0k0AjiWHvgP69x8GMkF9gB6luffSBbJ9T6Bt4qXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T06:12:56Z"
  mac: ENC[AES256_GCM,data:IcILG3hl0EP2d+JDYH8F4uMwwqmMRNnEU5bf3XHYTwuVbbIP3PdPfIi2KkgeOyPuBy7f9Bh019oL7LLL1CtX+n9RJmdnRcH8eZQMGNHJYLdzVpZxyLsi8PPe/ry7c2z/CSXvbNbNYj3LF8wJKT7//iKIqJzuE57WAmlYlD+FO2I=,iv:wZQffwCSOKj5ExIeI0tOcsKkhEyP0mBKvmaCJmuYavk=,tag:UM3QSXcr2K2U8lgjtay1BA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
