apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
data:
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:K3n99ERE25J1BSdZrN105NquIXw=,iv:NETXp5P1tPez/Q9BoCVjU4jqb9KvQ/G1N+t3Y1FBr5o=,tag:u2kf2KHcTz6IwdHesi4Qhw==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:RN6sD5ZOntDEIBgjEIUWskLWRqkAELOV,iv:GCBNJiQf7lcBjhpwh70WQFapionD0Wy1MIkmKLPPXmU=,tag:VB9ya07ayvmLXAVOeVErZg==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:v8/lJRbgmRzHLBivpfRTZU7xOVfOQrcanGkm65fBBIi4,iv:I7qyHH21andXbdUfQ6bzc8Qk5tzJV5U4Hg7r77Dk+wY=,tag:7waLakWxG79MDyQ8mRKlrw==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:ZRJbBAHshC2hX6zgojU=,iv:hhQ3QqbId6/yY3bqr4fNSGbzNqyc0bmsNCdYoLj9l7A=,tag:TizaYs3eKWttF57eltp69g==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:BLOK/j8v7n0AIITg8F+8DB7eeJo=,iv:n1wVoVSqbb0JnuS20oo/WtRl6i1lZRh9vYoCRGTTDk0=,tag:BfgYDDRNOrn06ZcEH+0AJA==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:PqBlWL1UAlk4II7gjblzX4fs9ffy6OaD6tdR7gpVH0v6YEjR/lPSuIAhiMdLQTros0Nioht6tMzsTq/JLdOxnTa/eBKGYVH9kQGDUyXolswDBo9l4vmL,iv:XrhMSwZvZMPHDxcr2scezkItWMmpbPre73eobCS4DeI=,tag:Ck3XRntsBMQzhTW1HXIPfA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:EAt3nGk=,iv:61veb61OoGrNRmFdX3ZtNBP8eAVxC8Dw9herQtNj5s8=,tag:XVUEJSv6z4YCBKh5zm6XAQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:TjlKlN7k+WQrExhboloJqhbtO24Z4It6MkmgkbxMYK0TqbFSPNPs,iv:g0vYnRVVIlP3V7rdbXJxmN3XtD0AFiFy8KeMjpC6yj4=,tag:Tm3TKyjc2Pj8OLoYMr4sCg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:/iI9QKU=,iv:IGraWgacL/ncBL6gsA6InaZ9hgg4JwtEjAaAam45Fhw=,tag:fRnqmqG7b+tgb4hsTBvUbg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:W4+eP/AZmufdL0kxT5NwSJ70ZpM3WxeN,iv:xTcHOYN8ic7X/Cib04sU1/F/ptM/cSG6xVJcRYDGMrM=,tag:U6BbceZ+2o59gHAPt/q5VA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:OUsz1xUqUaaOz6Yq0Zc7AmxOxvaYyXQt,iv:ZtpVmAez22tVqdk2MKOyJnXVTkQaM8oOChy+6Qd7Sg4=,tag:qFfQiTaULX1695Bzfo6d+w==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NkJUQ1kwamw0SkRXdGVN
        cmFVUEZOcDdhdk85RFJEYi8zaWhuK0NhcFJBClpTanZ1WjloVGQzWmpPTHM2SUxu
        NEV1ZjV6aU9SbnBFd2dZS08xZWlVWGsKLS0tIEMzNHdZbzFBdkhMOWFkRVdLZUNQ
        YTFKS1IrWUxTWk5XakwrWXgra3ArRVUKXxig2OeBAbSJWX0T/ovBlLl8owbjMhOo
        DBgxeKDWnRSA7CzkmP9KLP7HjxXbDoJBbxJbIneMQ3f45MNI15vlqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T06:14:15Z"
  mac: ENC[AES256_GCM,data:MAkw5p/nHb8M0HiFaHMnawk7mnpHkliqTL00g8w4oddBd2+WoYzD1IB6poKrBANVvglZwTYFfK3+xcFZVqU4vfMVwotclXBe9ScQiOu4aenlCuOk7G7nWeU/hczylG+xHpef6pXt6apkA4fdAlMwerWdK1Cc2bjVh0MAzEEJbvM=,iv:0mRyRn4BEGnhzqTXcH6RGqLX+1D5scfgTcIme6Svh/I=,tag:av4jL2W8bMq4HgPSNpDVlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
