apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
data:
  #ENC[AES256_GCM,data:cl1Ckw==,iv:YmFxz1tnuGeXagNTThRBO4rJ5/USrIhfSI/4m7PtA+c=,tag:zF8u7GW1Y5DiiF9FfSFh/w==,type:comment]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:1dNgRcxwNL2fiXavXtTJJnOT3iJOgw485sQURKpQ9lIqcMXnmukh7wSRXx4=,iv:p+SC5/OZnWIERqPZQq4tWWMEyMlrmzSqq8LigOrkVUk=,tag:Z1lhZvP/R5r8UbUKQGCdtg==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:35fRW7QdqrzZ+PuRME2f19p5ocx0rPtxpnJ1XSuxNDQk+yYM,iv:OAFLt8E32qKxd9i5QB955vJdZLJGPv0U1N4CIvolEQo=,tag:sr6h2q6OVjd0IaAl+nW3dw==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:Ccgs/+6MWO6F7wWGLg3VNao4p+0o0bTxfM6cm17+mZKv6l/axkUg2OMzdGbnwJO2,iv:KEF+ied8jPX6pZCM/NPLS/UdAytcFniitRgONAbMMpE=,tag:I4KjNlvZUbb1KFaX49tEgg==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:4oEoZ+vwGhkpXFYkZbrXiJOoi1c=,iv:JbRnAVeX5E3hT200Seql+pGJuXFsw+PKcK2l4WTzFUY=,tag:tHMNBqYs/QgC8c+/Eb2log==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:/eIRT27tuDoLc3Z+7LFwstNk6dmhAwnayRdgYH14hcb6aKa/UHUFr2i3Gak=,iv:QqtxwBj8ck4+NXfcy5TtmZ9kZkX9RDu2XJ79kaGmBQs=,tag:zfWn6ttcJ/BOGTpBay+g6A==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:+RHjwNG5I6XfBVoTQ6yJwZdZgVCCZTowYWR1N/PmawoQDjSzAhZzrd5qexUYklKKRrDz8zt8UUP/U0SYhA0YyqPvZIDcyGUlfKCgskcRGfWDrbBC5OFJKFRIBVnXRnnAhODia0axXyh81yOcl3W8tNrOXB/1P3BV,iv:mOvkhUmf9WPxCyy7NwVSuhaE0wYl4pU0mrl2wnzB6CY=,tag:ETiM/C4Y6LBBAJVCnAdpSQ==,type:str]
  #ENC[AES256_GCM,data:FYbrv73MEa5pr0T64d0=,iv:IAL/fDWZpfkv/R2r/pOvLtf45ewhWWY5VRo52IaIcX0=,tag:PhsX5uRPujpQYwbXeXoJMQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2Tw76FvbqXA=,iv:i4+YSstwa/6oRw5HkL7EeRHCRnGt1PP+/MtWzg0Srv4=,tag:eIBbnGsNv5pQQ/8ZtqM9og==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:A/uEhhPlVk3C9lo6GVZn/H6pKCUQlk3KPH1MvvTNMvHj31z+FJ88U8/SpYsRNdRfnLX4pvxUeg8=,iv:mtmmrmMPbSHNWolrliWYSV7eC6WwQ/9zPoG7UaU1fdI=,tag:VcZmLX4Sm8MYBtc/VGubsQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Iy1WRPh2apQ=,iv:u3D8neurqcPjtUkWH7jzrdzyDghKMaviVPNN6vb3Jo0=,tag:U9/O/72bpLyPI+/5ZzBDXQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qtViiLIaXYhBJ6jAwXaziYrU8DcqM9M42cIAKKP/L/q6mSdq,iv:TdAg2YYSYCrSByV+2yFLav/yi6nYONQ99HLi8ryKivk=,tag:LVoqGZp+R+vyxG6yI7AYPQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:sh236nD8tIrPrkSl+DvdEnXGvM7kLPjW3YTSo7dA1nqHGB7b,iv:eXHOfpAfFQeRopM+gSf1AfOdOSo5VLd3bISHR6t5MSs=,tag:XHJwzrdW5OIAAZTb9Bd+fA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMXFVWEF3U2NlcDcxQ1R1
        Qzhma2lvQ2pKeHgvSGFXUkhEN1laNXpya1UwCkFhSjhqazVUbVhRd0FEQ3B1Wk1W
        OXA0OUZxM1k2am91WFg1SDFwKzEzSW8KLS0tIHlYZ2l4RWtGK0VqSWorWXRvRzFL
        S3cyc2VXZXJXNUx0Wmx5K2Nla1dSNkUKoN3+ol9wXyzRmS0WL2C1Wv1Hngv6j0b+
        DCjPdxsfrfXj+L9DvIfAqBaye6JfltNfcR+ZcRsVyibvh2bb5WXzcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T05:08:43Z"
  mac: ENC[AES256_GCM,data:T0p6lkgayTIDA3uqQIbabcTOMW7AbjCkeSom5q3oSZ2fmRZdLi/U6mU22uvIYSluB1eojsGvoQ55f0ffIE02YzsH/LNz0WioNaMms37V8dyzsIoTEtGNODFTagphTIP6+FcTic50hIu7+N4ncFwbJcgjRVDKt7YDAgA7PEnBS98=,iv:HtAI2Lfrl3655vYBuuG/gB/2G34kqTG4QCw86jFk3uc=,tag:nZblW5Xh4EHO6yMNRQmD0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
