apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
data:
  #ENC[AES256_GCM,data:fQao3A==,iv:LhYqwWNx28a1Y4gVdnXuJqY3PqEA5tQ7XFIl0biMOvQ=,tag:TegcuXsOYIeNOFYlpzZOnA==,type:comment]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:9i6Lwo4zzmYGUL0OPf6VkcsrcC0=,iv:w+zEDC4/KdJEOO6giX9y84occjdGMeXcU5u/yFIaWhk=,tag:WLGtKEhMJuGxoLMIdFcWGQ==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:H2KRxu6STxiNLt0Xvu17BpJCEgdZuid5,iv:kwtuUfFTrmR/bnLoM38qy1zsMEVzdvCrXG8WvpqYv3Q=,tag:HWtxk1BNP/eUQHNeolrrig==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:cAw9ojUiYXp0i0Hr1pCJcXxL3xAeTn+rD/T8RG/2GmFP,iv:SELP44uKG87Fwbsd2SqrzSh3xYib54/v38KFUNcOq70=,tag:Xc79Pdn3iAf7U5u4kQU0yA==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:2FShgqDmxiiJxSbxZyU=,iv:NymdUhPl6rUY7cuV/goyNq082lwfapTMzjCOWJ51GPY=,tag:/z3ovTaMaTMuX+OSDaHE2w==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:izmtAenIanVXUlhp+1+6F13oyCU=,iv:yK/FtzxdAhg6q08Q4Xly5pIYuJUom7P4p0BH33oocvw=,tag:AJ1uWt5i6z9qvKffYQ1cGg==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:87imMXMiUqyOIfA0u5N3HRWMk+xwdseFXWBdQopGgo+X0zeNuixo7gvuvhZqb4/l2t0U0x3YHJh2wf1Xm8fLuscMmosTOoOJjmmo7fk7eel75q2FqvV1,iv:OV2/eIfzeTzOg5xH6PnQrmK1ZE0I3Bb0mOAQIihKSCw=,tag:GTohMJXGmPTzDJF4hoghcw==,type:str]
  #ENC[AES256_GCM,data:jOCie2Ms3EBZ8qyu8Ig=,iv:QtvT6eHvuW93k6lJuQtYfwcHfpJOrnXfeu46f5YuROc=,tag:DqgcplLp7ynP1dBtbSZ5ug==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:GZJpU/o=,iv:qFodkFsvbXUsF1JszqEzQBY7ukj9EKWi6yE0rfuyblw=,tag:JaPFVoXYTvXXn5H2NcND5A==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:aDuE/QQYnavmH89Jt1RSrbo3ayzIteUd23qGieTKkVbuTt4xs5VO,iv:nDmBcfraTEC6TPwc9WtzdyZJ3nwXil7vFU3o2G/ChQI=,tag:1Da3vbcXoelRJkz0c1JeJQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:je+lYXI=,iv:IT0W7+p/VdGunBJR10lIF9/S+7E7DfofCqhD0nRAigo=,tag:GxGIx+b8jACfLWw7EFXUQA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:yKi7R6URuRotTniJX8oW67QRxaAeiO0G,iv:pgfzyK9uQa/UxfutijJ0wl6HBXMhTnVLzPDCHF7wwsU=,tag:6xMKX/XP7cMf4k4ORAu1iw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:d+gdk8y8P81ckanbEr2+MOtS8RLSkqKz,iv:Zehdr1s2iiC6x6Vu7LnfjCfWfjs0ykJF/2Se1u4xa4Y=,tag:w3NiJiO00IKsRWaO9mpxBA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT2NLWktWUG9GU0JNVTdR
        WFNQTk5kMVdLeUxCYldZZCtpUlFQM1F1R200CjhGRTJBL2lHY083Y0l1ZWNta21h
        UmZEVWVWYTgzcjRpcDhoUkh2TTVzQU0KLS0tIHdlZGRNYWduRm1VNy8zTW84VEs2
        MGx6aTU3NzZucENyTytwRTk1V2pFdE0KRc29KHrf2XaWz0+4UzUdvhrymOyUZ7N5
        BNyWOJr+fHycVpI4w/j1wGouuuDpsuFw3DU3czi0TMaR4jFHnna31g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T06:00:47Z"
  mac: ENC[AES256_GCM,data:sDb2tT0bbjPX1k6BK/V2A2J+Jaq4R6d+bsArRCjFHsW0EIT2HgMZ7456KpYCIZK+/AR8mupZsYRY05COJcZmdIyvxJa6/0t2XbgaI9Ui6T+TO/XkL5y2r3SL8Dex6Z0EA2Q6fvDpY9CYkhfqGgrBuoKymvEA0iS2QtBTtYYTS94=,iv:lr7S2Y3H8kfoM/9Mn7QgnWeS3YVI2PA0shU2koTFDg4=,tag:afBI45Kaj+MYcpKLoLrAiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
