apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
data:
  #ENC[AES256_GCM,data:dn8p9w==,iv:QZSvE+cpIv8jEejiKlsVkisNo+Zz7/DF1lSm73d5ZTQ=,tag:PK0OxCvrdfiCnG8MMCCM0g==,type:comment]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:K+1MqVD+NKAC6vfWtX15jzC3RbY=,iv:SeveFG7FxY8YRKaoawHeb0+K7u+mPqVnhhMg9iqieEE=,tag:6IgUfaOR/wPeAhGVCC3ugQ==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:4741gDEttFae1wCnoXjgqwwVMffBv8L+,iv:BrwiQprQawfNQBx6uEvlGXeZ/52H1NxtWSxRyl0e3cY=,tag:pM/0z0Cl7wwtrEElim8Mkg==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:lof1EZhYXA5kW8JvsG9Qrv0rkGvo4knnI3bLJlZzzUPh,iv:ZcRVtzN4LUUZFJyNbifOYgt5uVoLukw4k3CulN9NbJE=,tag:tsPd438CQpqvouVevKaEWA==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:EmjGGu7wA4KfLcTXTdY=,iv:7omVG5zIdbuWUu4k9QDpWNjRbtEhw09q9ACR2kMYUjg=,tag:mWs3Ns429A720FxvGrx61w==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:LmYqlphuOgH8GQPKDgYcGZFiVW8=,iv:+IA+B5++gRUeXWlwvwFcg195z5X9Qu4XIEobkDcnz+w=,tag:3MMvXJoOeQ7sbjz94p26vQ==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:V3BvvL+zZKHyMLw9Yay5TsbCqjMxlMfAVI9oCFh6IY6MjprBtmk5cLfcozjpDlfvdeNoS65kyRKgtK2OTyekp6sOxIV7xXvtM0Xf5SEZ0jIA5wUYT0P3,iv:Tj/bhezqc7LM6hCHTthLBsjEDYv7pXFofSjrrVpncd0=,tag:mBiV9mjqYNploh/uWMb0YQ==,type:str]
  #ENC[AES256_GCM,data:RCHWJ1gIEoneaPYdyT8=,iv:6Mtm7eNCZk3aPpltwMm7be0Kzq1Z+uGlRt65DYnw580=,tag:JiGU8QXQknEPojLds8k0Mw==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:7ZxE8Ok=,iv:uvPLZHv1ZwDjv7LwxrLWKpueBRRhL2Nly10JqerEd2s=,tag:9ALF7V+TT5HJ9z0SzON5qg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:UVuHV+/ks7qotaOD+8gPobD+VIxkK7dD6u+Z19v0rjloHY0vRDpX,iv:E005/AWgrV7zXVSry7gZalYTY4+jERehEmpqNzZ62uY=,tag:a8fAkwjeqLlMoULU61080w==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:YpbM6ZM=,iv:sd26NH/86L1wnjF2rGv08j7jc7xR2ForgNmOjRnBsHI=,tag:NidMaf3BU+vKvNV9b/Qbig==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:KZUejr4c/PHbhRb8vGGvQmtZhegiKTY/,iv:x6m71mSyd1nESq2GLp4+Mrr0+16u3TErg9jAO+5lNsE=,tag:4TsKMlAQR+/h5cKqVL0k3g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0E8vcNn0Zt8a0FklhwYFzKR98JCMF/0W,iv:VGUZ3IFWDN5D/2XX1jmBjnmgiQysJZCf0s5Gsiyy7y0=,tag:kVnkWZoWuzgrIW+Sm+gtNw==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscjY2YUhteHZSMTNOVUxR
        TXAvKzlNOC8xYkR2aWdUa01NSktHTlVFSUZZCmhKM1Z6KzFuK2hGNnlJdURBRkhp
        WjZwdTJTSkQ3aUZXODYzUEtGMUpha28KLS0tIDRycWpSaWx5N0h0UCtIWHNYS1dE
        cXNxRXZYQ3FvcURCcHF2K3pqQ25RSjAKE3EcKc6e/8o94Xj58PqZEHlo1sfNI9oX
        xTNR9pbeGP0pe3g/oRhQDdMYqHRaCR3yEzqfIYcirxMITnR5Iyzpig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T06:08:41Z"
  mac: ENC[AES256_GCM,data:qiTvE0q/sDT3gdAnoHKMqiK5HHtHjQl1+kGoTMtl1tKZnSxyLmnhry4cIa1Rg4hAOHhlfGiIn6Wg0Obw0JL7+OOpBQyW40bdMCmg7TuuvrxWhFbV6/o23i68L5P3HXjI93F+pXcwt8ZXuPlcTjJrevrm0rcM068Nk6fc/1TAAoY=,iv:vtBWdwp1B7B6XKZ5Gy1L40i1ejlZwSeSDDb9IfarApA=,tag:8028Gr2hCs7iYXyxKi/CVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
