apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
data:
  #ENC[AES256_GCM,data:ALTi8Q==,iv:QqhTAhDoH/iI1ZgzjjakkluMyfZpogHMQuXxsmERlkg=,tag:EkWwyGfP4OdfIEDaWJYATw==,type:comment]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:AMg+nYqdLcvPJSWQbVL1ljxgYkud2HoSttEdqK34lz8=,iv:cGpcuMSDdkc3db4V+4hfNstk9SZxhorxHTN/Hntdjwg=,tag:eC/gwyk+fKKVRTMEQty6JQ==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:Eg/AQ0dRBq0CCilwsxIcBX3TAV5QXx+W,iv:F+9DUGiHpEYmTjLg0hmnVNlCKT+RA2wNqFm1eNrt9co=,tag:8oDL4V5QQwT4riuerAQvTw==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:32DdB52xcb3pszKW2V0aDHmKMMU7KbiyCKkMn67LgyPE,iv:WLfG1tnvBva9MwDOPOc5/ce4u4wS79YCwuQmUbiik0o=,tag:lp/XlxfpEn3s4JF75FAr2A==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:VeAODilbxZP9laJ0cgw=,iv:s6Gj3tlrgFfauYlMKe/9+EdSCd7lqQqLs7N1ImPGpZ4=,tag:XbsOxTV9M5fbj21SmqbZcw==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:RfCbIxlEsZLwfI32Qs8t1UVYGYXn5hA5XatLDIKNwPU=,iv:/Wb+YdM0BVPqvN58tIuc5/I1OIWFvGHxcEGROjIPQjc=,tag:v+D4D2br3JEQ1+klNQcHzw==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:zULboffWPEwmlQ6lqMpE2VoyLV4+oPjG1imXyrs1yvybYs8t/IxXwzFzXZ65CMd7mfeMEk2YBrTfgOILQTRt/MD9BFU9ceTKFMGDZwNYKU2zbJnNFHJj,iv:FgaLSHi1G41hrh5jaEHhbRNioY7QOrhQqPlKalUd+2A=,tag:PKAQe3jYn81bvcXhe8wBxw==,type:str]
  #ENC[AES256_GCM,data:yPXnQ19PyCIYkdkULig=,iv:TBmmwjpFChf5sC2qvR+mq5D661XyWz6wxluKs8mj8nA=,tag:pIkbdBcyfGN5Ma3g0AALUA==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2vdwI8w=,iv:Q/qUfka7kgqGtuesSj0Wfnmo2nx+edQ6b7JQhOOTzD8=,tag:J9IElh9DmHQyDDk3kBTDdA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:P+AsGKflYUOZDNESENltw+ikXsrhVRna+7iTGablAZ1dGJlIF8Vf,iv:PjwRoo1ocrEyjJT3cRNCNiSo0yCNGPRIzak4aY6GMZc=,tag:Jb3C58J7Hz+uGvvsj9glsg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:zY4PoyA=,iv:NAjU8bU8MlzrhqF9dvgVIFCPxfRdYc06GWQJWG9FlLU=,tag:qPeWgg4APHrP1QeHgQT90w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:nK3SZ4isoTinpksUtjvxgtjd6PXk1RH2,iv:euBQeXzQ2qP1MnX/ICnulGN7T2t8SG68BHmUQn/PGRg=,tag:JEWnYuLhE8ni8lYCvSLTtg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:cWVTY94/2ZEdn3DFmTAmSxglYyQHQRwx,iv:mKqXvJi9z7ECek6dbRImi9g1yBoWcQBmxL1PWhIclYg=,tag:iTRpsv7wp/G1qCPzqDyoOA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WFkvMEliY3dLWXYyU0ww
        U1dlSzZSVEpKbGEzb0srcytZVkdtMERwTTBRCi8xT2UyaEl0dkh3NjlZOHcwZ2U1
        ZXVHanhSd014d1BFWVoyUnZnT2lFeXcKLS0tIGtpVlB5aUNFcWFxUDZsQnRJZE41
        dDh2akhrM1M1ZUpDMWMxMzVWc2tGTFUKCA8xSNvvzXr6pZbXVPfPpf3SPorN9tQ9
        h65SNjYoPl8ZeidBbyA79A3PEpBNUuZSq2C9P+RcD68Rs6x93n4Etg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T04:50:44Z"
  mac: ENC[AES256_GCM,data:Xo2iRhvYwLJ9IkEWHwQAwd6aqwh+NChsqzla92+ByL6B3dKSm21bbHLpbTahnUoIwRI2sn/d1qnU9W1tVSaIkPE2Rtck2eKwURLbZR6iU3+5Xyz1QMHoF2p3Z+z/RquwIl4yYQwcik+tNAT3aNdW9fA47B1EihEB1fb+MH3CPdE=,iv:kupz+0zlr0b+VgebRCv81JFVfdmZKWvPgjzV7m6f0Vw=,tag:1RjPCz82Z1EQtlx2lLFGgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
