apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
data:
  #ENC[AES256_GCM,data:tYsFJQ==,iv:isNZlbKdB9SegSoufh1MvLdQ/BUSV0sftNDrlrvQWF0=,tag:er1I8Syct2tOJv4g8XWhRw==,type:comment]
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:ds9qqnOLfss5PXh+EWdI6HRKv74=,iv:AaXf12ym9KnQrVXY/SHUexVS8Q+gDup1X6S5NPgfG1Q=,tag:m+SyEOiFl6Hm/a5Ap0EPog==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:lCExnyklv3LNq1dD54JeI0k/2ulFtrTw,iv:BAPJNpm6vFaAJPnidxOEtjN4HH2Vqqb3gfGnzBWkieM=,tag:JGyg49zjCFjwQzOdwOu0yQ==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:RscOkDFjCvJWnaZKVjHQ3Vy4G1MqbkMtVzKzjbjS2ZjB,iv:r6u8aF/Z7B0Xv4h4GDhVtWbsARFVbH+oUThWdSJrkW8=,tag:fvrAr6/wnKNDODK/ecLn+w==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:BSUFmEvk8DWCPjBZzRw=,iv:rV4r/o44sJ46l9EM+SZv2aVXwEv+ErSD+1oPgzVtAOQ=,tag:MQ8rKE5dZyazswMnUDhPdA==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:BxnzpZStt8M1TWqH1p3PUeR8Kuw=,iv:ju6FMqlWJLwFo9jZmWqrf/1ga9xrIhE+ch8R8BTNFYo=,tag:S5TwGNJy3c28AmhWlQGNqA==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:VJNq88FvBBqYnk30t5M1xKYHgkilH+ebPtV7xyVpFsn3W+GfDwDkxBJQXwDzO3Qs28Cs6qFYtvCq1TTKmugWQmQ1e+mI6E/CT6yAoNHsXjoxMVFhdnZU,iv:8tJrR5QHwOQPyS2mgpXlngcazZVsoMDQ8DhvypdB6Hc=,tag:c3SfD4XnWJ+IWF7jrWmdgA==,type:str]
  #ENC[AES256_GCM,data:IhKYb5G8G6xSzPhwlTk=,iv:AesFeBntN6io+1u+Or4XHInLLhhQK4yrt/EWpRQk/s8=,tag:FZCLnPG9LR8IuGLoq7mQEA==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:MYFzyw4=,iv:7jAnnHuG/Z5f+rl7JpFiLGVlXMBHsfX8HYCOC8/IsD4=,tag:SJSKhvYuDjwBHloS9KNvGw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:zRd9bnCsfITKDHd+l5cg+sk5hXgqARvm102D7Obq/ri8Z4jcTAj/,iv:qmg/QP1jLF8/3hfM5U74kBVhtR2QTZXvSjGCnh0SGaI=,tag:VwBiWMqnWetmBbYRc/n2gg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:VsymFPA=,iv:bgh0vdCC+MZfw4wJOxOF65NkSC5dxECGvY1CYnuYkLA=,tag:L53NDizkG5rTuZg3PiSTZQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:unKkybqvk2hOQ8VQjl2/+CzUUp8wMO7X,iv:DDz5hvkrZXFKISnxrSb+nU3sPEtcrd/Q9gWynnSXNnc=,tag:FttIVLhyu2V+OJfHnWUzbA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:0eLqHjswCzghC4O4YxalH1a3bu2gHh1d,iv:LjPUokcSxJeSrlHUqYfVNmeUGcY0D6MMiKFKpprFYVk=,tag:BfzVHTcC4PNlWmniBrVwWA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVlkva1BuUzh2Mm5RZXN5
        amZXbU00WTZhaTlqS0lmZjRraFhYRjM2N2tVCjlqd3ZBYllUUTlVYkpoWllKUkNQ
        R1R3a2JPbUlPd3N2LzQ4Q2JRYXZ0bkEKLS0tIGprM2VVOFI2cU5XTlNyUUxQR0Ni
        VXBaMEFsMll4anVwRWJHb1RiM1VMd0UKNFh5z2xXmk9bAYgo4sL5f/rwu7S4pyUL
        jj8eTVXnz3l0kf1F0QD8eZgLJU9jZ7+57r9QwtciuuY121ULHuVKQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T06:10:08Z"
  mac: ENC[AES256_GCM,data:nDZDsrbhCuM3n8gZOsJt3K2/jiyvY4NmFGttamjzWDpfS4CWVA7fBDzPSYiBLxifpAyoo5RvHcNpEpBLRdIYXqAHfKfa2kB1QqeKE8LrSV8bT5g4uUiCWVigP+hhq5E02nhdVxP2VzlpashoA1AoUxiBRfmsU/EDBUUX2Oa4ggI=,iv:NSNK2I1g/nsgVwqOds4vP4557Kql8Vt0AxLwsmmuaVo=,tag:lGVvbYMiLYpce4GOZlIDog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
