apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
data:
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:gK6unrL+wFu78VteqZOZgkRUInwHxLwP,iv:zhITiRvGIwvs7nQ8WMjBfHtPculrBwzivcAuIuHGZyQ=,tag:UXfXTStETEOTyZae3nxAuA==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:COC07VFnmj9bAA+tNlKnppii2PL3N8oC,iv:vSeFzuFXxzdZwGsWuKRSk8hyPMpFDDfxfazHBTg4ocY=,tag:dsrAjS5AH7GWycmZF7w1ag==,type:str]
  LLDAP_USER_DN: ENC[AES256_GCM,data:WTEoa+oOqS0J6iDvbG4MFJRlmvOTx7SCyo0dUF5p2Cx9,iv:7xMfZkzViRS3XE4b527iJM4yDYQT2hNnnzgv7kVjk7w=,tag:x7h+kS/8ePFlvj4EiAxzIw==,type:str]
  LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:XPlG2D/cvZgQGOnePq0=,iv:M+kmy5yjmiBcg61zKZ/BonqPkILHBZN8CUE/Wc6eMW4=,tag:m+gDgGFMgusICt+g882rNg==,type:str]
  LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:DNEq8/lRb0Oe4AqnD9ni/DgnxUdv9X2e,iv:w5VdX+F+jNQJq/WroOs8sIDUP5TzX1xvNQEs/12vKfg=,tag:jYtkU3yYF2MPA2QOtWkXAA==,type:str]
  LLDAP_DATABASE_URL: ENC[AES256_GCM,data:w/CX3+1p8IyzMOKyy2wBahb3v/WA/heSjf/ARnTotxG7wj3IwzgNrRjPrZAEUMX3EU5hROO1E4PCrhzrimUYzRcFQrAe8rovBMk/mmQCgRL3NRKJbQS0,iv:0JUtS1+uQ/+WA9RugKm2jCvOSCZifs/P8XzS5Ej1MhY=,tag:OkLkmXEpFGJPZPmrTWJQdQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:oj1p8ls=,iv:Dh9ekr//iwHA5QJ2sqDDXrZFZp0Re4861lUg3bSuXks=,tag:+EXURY0ae+JF9zCfc3q5QQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:74yzjnMH9JbrAR+aBDqP59mMn2dl1vhTV7ux3rIw4N4t2B9oDns7,iv:6crebNhaO3+7ZotqkAgrOC65o34TJOwF1U7xtfgx7MI=,tag:WLdHJgMujEkSPtQGvGn60g==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:4am22h0=,iv:nKrL3iGBT717lQKFr0FwfI6h8jMRQKA/8RS+MKWKyn8=,tag:Fh/9bMfHLHJbFdaPW742ug==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:2pD+1EqSZbUryJV152Xr/GQ7AQd0s3pF,iv:7Sk1BnfqcTGUEg1IloAMoOup/oz1s+lJzga2X5fugpg=,tag:Has/G/QYABhW58GUXzKjsA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:s7LSqJ1Td89KGfkYg0UrGSXy0WNPgRbX,iv:iuWS68VpVRHwVKRLwW2Af69bWbHTWpQIqHtNg8VJ3+8=,tag:aixRx7EeT13d+bRkPiL8eg==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MjhMOW9TZy80V0dzMGFv
        a2tuSndsMG9KbDlDZmQ3c0diM0pUL3lodzNNCnRFK0FJY0pVMTYxckFxajlVVnJP
        M2R5Y3RBWmV1QmZwOGNxY0hXM2JYMGcKLS0tIDJWRzZVSHI1MEFXQ3psbWZ5NjFG
        QnlyRUV4Vmc5ZndYRWxncUhxbms3NlUKStlMd2bGuwH4F2YXH9V2nDlwlsQMzFEW
        K5XItSeykvjoY4UlA+/H4ogMNpp5z5KT0/GnmsVBwauXhBPs0ZjwOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T06:21:01Z"
  mac: ENC[AES256_GCM,data:nY++/oZUqwIazg2KhR9FX726p3IIcvZoA+cfGDxQm+gP4ftULaavurozqd5T4aLN63n555NKrNunRDWXFSh4HLLy2tgNVkkceypDsEQWF20/F0eNGjUF32BnAxzovHlWgZl//80tskbKxAtSkOtKKK0SDjU6QXMsgBN8ThjsDO0=,iv:qvJL7ybseiiRfcP4JRNcOJ7b+Hv+Oc/X5ZgopMYpYXw=,tag:qx49IUNT8pgIz+DZ9lfoBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
